### PR TITLE
6 new App icons

### PR DESCRIPTION
**Pull request by iLynux8888**
I have created some icons I think would benefit this theme. I am not very good at GitHub, so I don't know what else I need to do, but I have the SVG files ready for approval. I just don't know what to do with them.
The apps I created icons for are as follows:

- Google Docs
- Google Sheets
- Google Slides
- Hulu
- Android Messages
- Google Duo

Thank you for your help.

### CODE REVIEW

**Comment by gusbemacbe** [comment]
Hi @iLynux8888 !

You did something wrong. I will train now you. Please avoid uploading the files to the branches `master` and `beta`, because these branches are for you to upgrade my upstream Github repository. You need to create the new branch.

1. Make backup of your files that you have created
2. Remive your repository
3. Fork my repository
4. Open the terminal and run:

```bash
git clone https://github.com/iLynux8888/suru-plus
cd suru-plus
git checkout -b new_icons
git push origin new_icons
```

5. Put your files you made backup and run:

```bash
git add .
git commit -m "Addeed new icons"
git push
# Type your username and your password
```

6. Open the Github site and go to your repository.
7. Click "Branch: master" and switch to "new_icons"
8. Create a pull request and select "gusbemacbe:beta". Ready. 
9. Once I approve, you need to delete the branch

### Tip

You do not need to remove and fork every time, you can delete only the branches you created.

When I upgrade something in my repository, you need to switch from the deleted branch to the branch `master`: 

```bash
cd suru-plus
git fetch origin
git checkout master
git remote add upstream https://github.com/gusbemacbe/suru-plus
git pull upstream master 
git add .
git push
```

**Comment by iLynux8888** [comment]
Thank you so much! I have done all of the above.

**Comment by gusbemacbe** [comment]
Ready! I merged.

**Comment by iLynux8888** [comment]
Thanks! I am happy to have contributed. And thanks again for the help. I hope you like the new icons.

**Comment by gusbemacbe** [comment]
You are welcome. I like more the icons of Android Message, Hulu and the alternative icons of Nautilus and Terminal. They are very beautiful.

**Pull request closed without merging**
